// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: protobuf/record.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp     `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Content       []byte                     `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	SrcNet        string                     `protobuf:"bytes,2,opt,name=srcNet,proto3" json:"srcNet,omitempty"`
	Meta          map[string]*structpb.Value `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_protobuf_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_protobuf_record_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Record) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Record) GetSrcNet() string {
	if x != nil {
		return x.SrcNet
	}
	return ""
}

func (x *Record) GetMeta() map[string]*structpb.Value {
	if x != nil {
		return x.Meta
	}
	return nil
}

type RecordList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordList) Reset() {
	*x = RecordList{}
	mi := &file_protobuf_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordList) ProtoMessage() {}

func (x *RecordList) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordList.ProtoReflect.Descriptor instead.
func (*RecordList) Descriptor() ([]byte, []int) {
	return file_protobuf_record_proto_rawDescGZIP(), []int{1}
}

func (x *RecordList) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_protobuf_record_proto protoreflect.FileDescriptor

const file_protobuf_record_proto_rawDesc = "" +
	"\n" +
	"\x15protobuf/record.proto\x12\x06record\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xf3\x01\n" +
	"\x06Record\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12\x16\n" +
	"\x06srcNet\x18\x02 \x01(\tR\x06srcNet\x12,\n" +
	"\x04meta\x18\x03 \x03(\v2\x18.record.Record.MetaEntryR\x04meta\x1aO\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"6\n" +
	"\n" +
	"RecordList\x12(\n" +
	"\arecords\x18\x01 \x03(\v2\x0e.record.RecordR\arecordsB\fZ\n" +
	"./protobufb\x06proto3"

var (
	file_protobuf_record_proto_rawDescOnce sync.Once
	file_protobuf_record_proto_rawDescData []byte
)

func file_protobuf_record_proto_rawDescGZIP() []byte {
	file_protobuf_record_proto_rawDescOnce.Do(func() {
		file_protobuf_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_record_proto_rawDesc), len(file_protobuf_record_proto_rawDesc)))
	})
	return file_protobuf_record_proto_rawDescData
}

var file_protobuf_record_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_record_proto_goTypes = []any{
	(*Record)(nil),                // 0: record.Record
	(*RecordList)(nil),            // 1: record.RecordList
	nil,                           // 2: record.Record.MetaEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*structpb.Value)(nil),        // 4: google.protobuf.Value
}
var file_protobuf_record_proto_depIdxs = []int32{
	3, // 0: record.Record.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: record.Record.meta:type_name -> record.Record.MetaEntry
	0, // 2: record.RecordList.records:type_name -> record.Record
	4, // 3: record.Record.MetaEntry.value:type_name -> google.protobuf.Value
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protobuf_record_proto_init() }
func file_protobuf_record_proto_init() {
	if File_protobuf_record_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_record_proto_rawDesc), len(file_protobuf_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_record_proto_goTypes,
		DependencyIndexes: file_protobuf_record_proto_depIdxs,
		MessageInfos:      file_protobuf_record_proto_msgTypes,
	}.Build()
	File_protobuf_record_proto = out.File
	file_protobuf_record_proto_goTypes = nil
	file_protobuf_record_proto_depIdxs = nil
}
